# Generated by Django 5.2 on 2025-11-17 02:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("content", models.TextField(blank=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("프론트엔드", "프론트엔드"),
                            ("백엔드", "백엔드"),
                            ("사이버보안", "사이버보안"),
                            ("게임개발", "게임개발"),
                            ("사물인터넷", "사물인터넷"),
                            ("빅데이터", "빅데이터"),
                            ("인공지능", "인공지능"),
                        ],
                        default="프론트엔드",
                        max_length=20,
                    ),
                ),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_post",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "boards",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_comment", models.TextField()),
                (
                    "date_comment",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("프론트엔드", "프론트엔드"),
                            ("백엔드", "백엔드"),
                            ("사이버보안", "사이버보안"),
                            ("게임개발", "게임개발"),
                            ("사물인터넷", "사물인터넷"),
                            ("빅데이터", "빅데이터"),
                            ("인공지능", "인공지능"),
                        ],
                        default="프론트엔드",
                        max_length=20,
                    ),
                ),
                (
                    "board_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="board.board",
                    ),
                ),
                (
                    "user_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
    ]
