# Generated by Django 5.2 on 2025-11-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="board_title",
            new_name="title",
        ),
    ]
