# Generated by Django 5.2 on 2025-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_board_title_board_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="generation",
            field=models.CharField(default="10대", max_length=20),
        ),
    ]
