# Generated by Django 5.2 on 2025-11-15 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_board_generation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="board",
            table="boards",
        ),
        migrations.AlterModelTable(
            name="comments",
            table="comments",
        ),
    ]
