# Generated by Django 5.2.8 on 2025-11-19 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_is_anonymous_post_is_anonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scraps',
            field=models.ManyToManyField(blank=True, related_name='scrapped_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
