# Generated by Django 5.2 on 2025-11-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_alter_board_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="generation",
            field=models.CharField(default="10대", max_length=20),
        ),
    ]
